# Gunakan image Python resmi sebagai base image
FROM python:3.12-slim

# Set working directory di dalam container
WORKDIR /app

# Install dependensi sistem yang diperlukan
RUN apt-get update && apt-get install -y \
    libgl1 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*

# Copy file requirements.txt ke working directory
COPY requirements.txt .

# Install dependensi Python
RUN pip install --no-cache-dir -r requirements.txt

# Copy seluruh kode aplikasi ke working directory
COPY . .

# Expose port yang akan digunakan oleh aplikasi
EXPOSE 10000

# Perintah untuk menjalankan aplikasi
CMD ["gunicorn", "--bind", "0.0.0.0:10000", "wsgi:app"]